#!/usr/bin/env bash
# Bash Script that retrives IP and QUERY_TYPE from a domain or subdomain

func() {
	if [ "$#" -eq 1 ]
	then
		DOMAIN="$1"
		for SUB_DOMAIN in www lb-01 web-01 web-02
		do  
			URL="$SUB_DOMAIN.$DOMAIN"
			IP=$(dig "$URL" | grep -A1 'ANSWER SECTION:' | sed -n '1!p' | awk -F' ' '{print $5}')
			QUERY_TYPE=$(dig "$URL" | grep -A1 'ANSWER SECTION:' | sed -n '1!p' | awk -F' ' '{print $4}')
			echo "The subdomain $SUB_DOMAIN is a $QUERY_TYPE record and points to $IP"
		done
	else 
		DOMAIN="$1"
		SUB_DOMAIN="$2"
		URL="$SUB_DOMAIN.$DOMAIN"
		IP=$(dig "$URL" | grep -A1 'ANSWER SECTION:' | sed -n '1!p' | awk -F' ' '{print $5}')
		QUERY_TYPE=$(dig "$URL" | grep -A1 'ANSWER SECTION:' | sed -n '1!p' | awk -F' ' '{print $4}')
		echo "The subdomain $SUB_DOMAIN is a $QUERY_TYPE record and points to $IP"
	fi
}

func $1 $2
