#!/usr/bin/env bash
# Bash script that transfers a file from our client to a server. Display Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY if less than 4 parameters passed. scp must transfer the file to the user home directory ~/ Strict host key checking must be disabled when using scp. Sintax: scp <client_source_path_file> <server_user>@<server_ip>:<server_target_path_file> We add the file path containing the ssh key using the -i option. The -o can be used to pass options to ssh, like StrictHostKeyChecking that allow the user to control if ssh keys must be added manually or automatically

if [ $# -lt 4 ]
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	scp -o StrictHostKeyChecking=no -i $4 $1 $3@$2:~/
fi
