#!/usr/bin/env bash
# Bash script  to automatically configure your Nginx server (when you install it) so that /redirect_me is “301 Moved Permanently” to another page by modifying the virtual hosts configuration file: /etc/nginx/sites-enabled/default and show a custom error page when the page is not found, ie: curl IP/bla_bla_bla

sudo apt-get -y update
sudo apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo sed -i '/server_name _;/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" | sudo tee /var/www/html/error_page_404.html
sudo sed -i '/server_name _;/a error_page 404 /error_page_404.html;\nlocation = /error_page_404.html {\nroot /var/www/html;\ninternal;\n}' /etc/nginx/sites-available/default
sudo service nginx restart