#!/usr/bin/env bash
# Bash script that replace port number using sed and service (init) must say that nginx is not running ← for real

rm /etc/nginx/sites-enabled/default
cp /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
