#!/usr/bin/env bash
# Infinity loop that prints "I am invicible" when receiving a SIGTERM signal
j=1
while [ $j -le 2 ]
do
	trap 'echo I am invincible!!!' SIGTERM
	echo "To infinity and beyond"
	sleep 2
done
