#!/usr/bin/env bash
# Bash script that displays "Best School" 10 times using while with exeption
j=1
while [ $j -le 20 ]
do
	case $j in
		4)
			echo $j
			echo "bad luck from China"
			;;
		9)
			echo $j
			echo "bad luck from Japan"
			;;
		17)
			echo $j
			echo "bad luck from Italy"
			;;
		*)
			echo $j
	esac
	j=$(( j + 1 )) # increase number by 1
done
